### ISSUE TITLE
Am I supposed to get 21 keypoints in lsp+toes?

### ISSUE THREAD

**Issue by mphirke** [russoale/hmr2.0#2]
LSP has 14 joints, and 2 more joints/toes should make the overall joints 16 if I'm misunderstanding anything. However, I am getting 21 joints in both kp2d and kp3d (size 42 and 63).

This should be all of them, right?:
0.     Right toe
1.	Right ankle
2.	Right knee
3.	Right hip
4.	Left hip
5.	Left knee
6.	Left ankle
7.     Left toe
8.	Right wrist
9.	Right elbow
10.	Right shoulder
11.	Left shoulder
12.	Left elbow
13.	Left wrist
14.	Neck
15.	Head top

This is my Config:
```

class TrimeshConfig(LocalConfig):
        BATCH_SIZE = 1
        ENCODER_ONLY = True

        LOG_DIR = os.path.abspath('/content/logs/lsp_toes')
        CUSTOM_REGRESSOR_IDX = {
            0: 'regressor_toes_right.npy',
            7: 'regressor_toes_left.npy'
        }
        CUSTOM_REGRESSOR_PATH = os.path.abspath('/content/hmr2.0/models/regressors')

        # LOG_DIR = os.path.abspath('../../logs/lsp')
        # comment JOINT_TYPE if using lsp only !!!
        JOINT_TYPE = 'custom'
        
config = TrimeshConfig()
```

Would you help me by listing the missing 5 keypoints and which part do each number correspond to?
Thanks very much.

**Comment by russoale** [comment]
Hi @mphirke,

yes 21 is intended behavior. This adds up from the original repo's 19 2d keypoints (lsp + 5 additional coco face keypoints). Therefore additional toes just add up to 21 for 2d. The 3d keypoints in the original repo are only considered to be lsp keypoints and therefore toes add up to 16 for 3d. Because the `SMPL` regressor is used for both 2d and 3d the model detects 21 keypoints for both. Like in my `model.test()` you should slice the predicted 3d keypoints to only consider the lsp+toes keypoints, see https://github.com/russoale/hmr2.0/blob/778e254e200497b0b6e5cac33901cf419ffa52c9/src/main/model.py#L415

Then the 3D LSP+toes order is defined as https://github.com/russoale/hmr2.0/blob/778e254e200497b0b6e5cac33901cf419ffa52c9/datasets_preprocessing/converter/tfrecord_converter.py#L347-L348

And for 2d :
```
['toes_r', 'ankle_r', 'knee_r', 'hip_r', 'hip_l', 'knee_l', 'ankle_l', 'toes_l',
'wrist_r', 'elbow_r', 'shoulder_r', 'shoulder_l', 'elbow_l', 'wrist_l', 'neck', 'brain', 
'nose', 'eye_l', 'eye_r', 'ear_l', 'ear_r'] # additional coco face kps
```

Hope that helps you

**Comment by mphirke** [comment]
Hi, thanks a lot for confirming and for list of the keypoints. It was very helpful.
